version: "3.4"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/quickdrop
      DB_USERNAME: bytebreeze
      DB_PASSWORD: bytebreeze
      UPLOAD_PATH: /app/uploads
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quickdrop
      POSTGRES_USER: bytebreeze
      POSTGRES_PASSWORD: bytebreeze
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
